Academica/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('alumnos.urls', namespace="alumnos")),
    url(r'^', include('cursos.urls', namespace="cursos")),
    url(r'^', include('dependencias.urls', namespace="dependencias")),
    url(r'^', include('docentes.urls', namespace="docentes")),
    url(r'^', include('especialidades.urls', namespace="especialidades")),
    url(r'^', include('grados.urls', namespace="grados")),
    url(r'^', include('notas.urls', namespace="notas")),
    url(r'^', include('years.urls', namespace="years")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cursos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^reportes/', views.hello_pdf, name='hello_pdf'),
    url(r'^cursos/crear/', views.CursoCreateView.as_view(), name='create_cursos'),
    url(r'^cursos/', views.CursoListView.as_view(), name='list_cursos'),
]

notas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
#    url(r'^$', views.hello_pdf, name='hello_pdf'),
]

cursos/models.py
from __future__ import unicode_literals

from django.db import models
from docentes.models import Docente

class Curso(models.Model):
	curso = models.CharField(max_length=255)
	codigo = models.CharField(max_length=10)
	docente = models.OneToOneField(Docente)
	vacantes = models.PositiveIntegerField(default=0)
	fecha_de_inicio = models.DateField()
	fecha_de_termino = models.DateField()

	def __str__(self):
		return self.curso.encode('utf-8')

	def get_absolute_url(self):
		return u'/cursos/'

cursos/views.py
# coding: utf-8 
import os

from io import BytesIO

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4, cm
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, Table,TableStyle, Image
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from django.http import HttpResponse

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from .models import Curso

from django.shortcuts import render
from django.template import loader

class CursoListView(ListView):
    model = Curso
    fields = '__all__'    

class CursoCreateView(CreateView):
    model = Curso
    fields = '__all__'

def hello_pdf(request):
    # Create the HttpResponse headers with PDF.
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=Platzi-student-report.pdf'

    # Create the PDF object, using the BytesIO as its "file."
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)

    #Header
    c.setLineWidth(.3)
    c.setFont('Helvetica', 22)
    c.drawString(30, 750, 'Platzi')

    c.setFont('Helvetica', 12)
    c.drawString(30, 735, 'Report')

    c.setFont('Helvetica-Bold', 12)
    c.drawString(480, 750, "01/07/2016")
    #start X, height end y, heigth
    c.line(460, 747, 560, 747)

    #Students table
    students = [
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'}
    ]

    #Table header
    styles = getSampleStyleSheet()
    styleBH = styles["Normal"]
    styleBH.alignment = TA_CENTER
    styleBH.fontSize = 10

    numero = Paragraph('''#''', styleBH)
    alumno = Paragraph('''Alumno''', styleBH)
    b1 = Paragraph('''BIM1''', styleBH)
    b2 = Paragraph('''BIM2''', styleBH)
    b3 = Paragraph('''BIM3''', styleBH)
    total = Paragraph('''Promedio''', styleBH)

    data = []

    data.append([numero, alumno, b1, b2, b3, total])

    #Table
    styleN = styles["BodyText"]
    styleN.alignment = TA_CENTER
    styleN.fontSize = 7

    high = 650
    for student in students:
    	this_student = [student['#'], student['name'], student['b1'], student['b2'], student['b3'], student['total']]
    	data.append(this_student)
    	high = high - 18

    #table size
    width, heigth = A4
    table = Table(data, colWidths=[1.9 * cm, 9.5 * cm, 1.9 * cm, 1.9 * cm, 1.9 * cm, 2 * cm])
    table.setStyle(TableStyle([#estilos de la tabla
    	('INNERGRID',(0,0),(-1, -1), 0.25, colors.blue),
    	('BOX', (0,0), (-1, -1), 0.25, colors.red),]))

    #pdf size
    table.wrapOn(c, width, heigth)
    table.drawOn(c, 30, high)
    c.showPage() #save page

    #save pdf
    c.save()

    # get the value of BytesIO buffer and write response	 
    pdf = buffer.getvalue()
    c.showPage()
    buffer.close()
    response.write(pdf)
    return response# Create your views here.

templates/cursos/curso_form.html
{% extends "base.html" %}

{% block content %}
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/formularios.css' %}">
	
	<section class="home full-height">

        <div class="contenedor">
            <div class="row left">
                <h1 class="col-10 title">Registro de Cursos</h1>
                <div id="form-main">
  					<div id="form-div">      
						<form class="form" action="" method="POST">
							{% csrf_token %}
					      	{% load widget_tweaks %}						 
							<div class="caja">
								<div class="error">
									{{form.curso.errors}}
								</div>
								<div class="input">
									<p class="name">
								    	{% render_field form.curso|add_class:"validate[required,custom[onlyLetter],length[0,100]] feedback-input" name="curso" id="name" placeholder="Nombre del curso..." %}
								    </p>
							    </div>
							</div>

							<div class="caja">
								<div class="error">
									{{form.codigo.errors}}
								</div>
								<div class="input">
								    <p class="apellidos">
								  		{% render_field form.codigo|add_class:"validate[required,custom[onlyLetter],length[0,100]] feedback-input" name="codigo" id="name" placeholder="Código del curso..." %}
								  	</p>
							    </div>
							</div>

							<div class="caja">
								<div class="error">
									{{form.docente.errors}}
								</div>
								<div class="input">
								    <p class="apellidos">
								  		{% render_field form.docente|add_class:"validate[required,custom[onlyLetter],length[0,100]] feedback-input" name="docente" id="name" placeholder="Docente..." %}
								  	</p>
							    </div>
							</div>

							<div class="caja">
								<div class="error">
									{{form.vacantes.errors}}
								</div>
								<div class="input">
								    <p class="apellidos">
								  		{% render_field form.vacantes|add_class:"validate[required,custom[onlyLetter],length[0,1]] feedback-input" name="vacantes" id="name" placeholder="Vacantes..." %}
								  	</p>
							    </div>
							</div>

							<div class="caja">
								<div class="error">
									{{form.fecha_de_inicio.errors}}
								</div>
								<div class="input">
								    <p class="apellidos">
								  		{% render_field form.fecha_de_inicio|add_class:"validate[required,custom[onlyLetter],length[0,100]] feedback-input" name="fecha_de_inicio" id="calendar" placeholder="Fecha de inicio..." %}
								  	</p>
							    </div>
							</div>

							<div class="caja">
								<div class="error">
									{{form.fecha_de_termino.errors}}
								</div>
								<div class="input">
								    <p class="apellidos">
								  		{% render_field form.fecha_de_termino|add_class:"validate[required,custom[onlyLetter],length[0,100]] feedback-input" name="fecha_de_termino" id="calendar" placeholder="Fecha de término..." %}
								  	</p>
							    </div>
							</div>
						  	<div class="clear"></div>
							<div class="submit">
						    	<input type="submit" value="Registrar" id="button-blue"/>
						    	<div class="ease"></div>
						  	</div>
						</form>
	            	</div>
	        	</div>
	    	</div>
	    </div>
    </section>
{% endblock content %}

templates/cursos/curso_list.html
{% extends "base.html" %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/tables.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">

    <section class="home full-height">

            <div id="main" class="container">
                <nav class="dropdownmenu">
                    <ul>
                        <li><a href="{% url 'cursos:create_cursos' %}">Nuevo Curso</a></li>
                    </ul>  
                    <ul>
                        <li><a href="#">Registro Masivo</a></li>
                    </ul>   
                </nav>
                <h2>Lista de Cursos</h2>
                <table class="width200">
                    <tbody>
                      <tr>
                        <th>N°</th>
                        <th>CURSO</th>
                        <th>CÓDIGO</th>
                        <th>DOCENTE</th>
                        <th>VACANTES</th>
                        <th>FECHA DE INICIO</th>
                        <th>FECHA DE TERMINO</th>
                      </tr>
                    {% for curso in object_list  %}
                        <tr>
                            <td>{{curso.id}}</td>
                            <td>{{curso.curso}}</td>
                            <td>{{curso.codigo}}</td>
                            <td>{{curso.docente}}</td>
                            <td>{{curso.vacantes}}</td>
                            <td>{{curso.fecha_de_inicio}}</td>
                            <td>{{curso.fecha_de_termino}}</td>
                        </tr>
                    {% endfor %}
                      </tbody>
                </table>
            </div>
        </section>
{% endblock content %}