Academica/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('alumnos.urls', namespace="alumnos")),
    url(r'^', include('cursos.urls', namespace="cursos")),
    url(r'^', include('dependencias.urls', namespace="dependencias")),
    url(r'^', include('docentes.urls', namespace="docentes")),
    url(r'^', include('especialidades.urls', namespace="especialidades")),
    url(r'^', include('grados.urls', namespace="grados")),
    url(r'^', include('notas.urls', namespace="notas")),
    url(r'^', include('years.urls', namespace="years")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

alumnos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^reportes/', views.hello_pdf, name='hello_pdf'),
    url(r'^$', views.inicio, name='inicio'),
    url(r'^alumnos/crear/', views.AlumnoCreateView.as_view(), name='create_alumnos'),
    url(r'^alumnos/', views.AlumnoListView.as_view(), name='list_alumnos'),
]

notas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
#    url(r'^$', views.hello_pdf, name='hello_pdf'),
]

alumnos/models.py
from __future__ import unicode_literals

from django.db import models
from personas.models import Persona
from cursos.models import Curso

class Alumno(models.Model):
	persona = models.ForeignKey(Persona, blank=False)
	cip = persona.cip
	curso = models.ForeignKey(Curso, blank=False)

	def __str__(self):
		return self.nombres.encode('utf-8')

	def get_absolute_url(self):
		return u'/alumnos/'

	

alumnos/views.py
# coding: utf-8 
import os

from io import BytesIO

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4, cm
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, Table,TableStyle, Image
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from django.http import HttpResponse

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from .models import Alumno

from django.shortcuts import render
from django.template import loader

class AlumnoListView(ListView):
    model = Alumno
    fields = '__all__'    

class AlumnoCreateView(CreateView):
    model = Alumno
    fields = '__all__'

def inicio(request):
    template = loader.get_template('alumnos/index.html')
    title = 'Inicio'
    context = {
        'title': title
    }
    return HttpResponse(template.render(context, request))

def hello_pdf(request):
    # Create the HttpResponse headers with PDF.
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=Platzi-student-report.pdf'

    # Create the PDF object, using the BytesIO as its "file."
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)

    #Header
    c.setLineWidth(.3)
    c.setFont('Helvetica', 22)
    c.drawString(30, 750, 'Platzi')

    c.setFont('Helvetica', 12)
    c.drawString(30, 735, 'Report')

    c.setFont('Helvetica-Bold', 12)
    c.drawString(480, 750, "01/07/2016")
    #start X, height end y, heigth
    c.line(460, 747, 560, 747)

    #Students table
    students = [
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'}
    ]

    #Table header
    styles = getSampleStyleSheet()
    styleBH = styles["Normal"]
    styleBH.alignment = TA_CENTER
    styleBH.fontSize = 10

    numero = Paragraph('''#''', styleBH)
    alumno = Paragraph('''Alumno''', styleBH)
    b1 = Paragraph('''BIM1''', styleBH)
    b2 = Paragraph('''BIM2''', styleBH)
    b3 = Paragraph('''BIM3''', styleBH)
    total = Paragraph('''Promedio''', styleBH)

    data = []

    data.append([numero, alumno, b1, b2, b3, total])

    #Table
    styleN = styles["BodyText"]
    styleN.alignment = TA_CENTER
    styleN.fontSize = 7

    high = 650
    for student in students:
    	this_student = [student['#'], student['name'], student['b1'], student['b2'], student['b3'], student['total']]
    	data.append(this_student)
    	high = high - 18

    #table size
    width, heigth = A4
    table = Table(data, colWidths=[1.9 * cm, 9.5 * cm, 1.9 * cm, 1.9 * cm, 1.9 * cm, 2 * cm])
    table.setStyle(TableStyle([#estilos de la tabla
    	('INNERGRID',(0,0),(-1, -1), 0.25, colors.blue),
    	('BOX', (0,0), (-1, -1), 0.25, colors.red),]))

    #pdf size
    table.wrapOn(c, width, heigth)
    table.drawOn(c, 30, high)
    c.showPage() #save page

    #save pdf
    c.save()

    # get the value of BytesIO buffer and write response	 
    pdf = buffer.getvalue()
    c.showPage()
    buffer.close()
    response.write(pdf)
    return response# Create your views here.

templates/alumnos/alumno_form.html
{% extends "base.html" %}

{% block content %}
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/formularios.css' %}">
	
	<section class="home full-height">

        <div class="contenedor">
            <div class="row left">
                <h1 class="col-10 title">Registro de alumnos</h1>
                <div id="form-main">
  					<div id="form-div">      
						<form class="form" action="" method="POST">
							{% csrf_token %}
					      	{% load widget_tweaks %}						 
							<div class="caja">
								<div class="error">
									{{form.nombres.errors}}
								</div>
								<div class="input">
									<p class="name">
								    	{% render_field form.nombres|add_class:"validate[required,custom[onlyLetter],length[0,100]] feedback-input" name="nombres" id="name" placeholder="Nombres" %}
								    </p>
							    </div>
							</div>

							<div class="caja">
								<div class="error">
									{{form.apellidos.errors}}
								</div>
								<div class="input">
								    <p class="apellidos">
								  		{% render_field form.apellidos|add_class:"validate[required,custom[onlyLetter],length[0,100]] feedback-input" name="apellidos" id="name" placeholder="Apellidos" %}
								  	</p>
							    </div>
							</div>
							
							<div class="caja">
								<div class="error">
									{{form.cip.errors}}
								</div>
								<div>
								    <p class="cip">
						  				{% render_field form.cip|add_class:"validate[required,custom[onlyNumbers],length[0,8]] feedback-input" name="cip" id="name" placeholder="Cip" %}
						  			</p>
							    </div>
							</div>
						  	
						  	<div class="caja">
								<div class="error">
									{{form.dni.errors}}
								</div>
								<div>
								    <p class="dni">
						  				{% render_field form.dni|add_class:"validate[required,custom[onlyNumbers],length[0,8]] feedback-input" name="dni" id="name" placeholder="Dni" %}
						  			</p>
							    </div>
							</div>

							<div class="caja">
								<div class="error">
									{{form.grado.errors}}
								</div>
								<div>
								    <p class="grado">
						  				{% render_field form.grado|add_class:"feedback-input" name="grado" id="name" title="grado"%}
						  			</p>
							    </div>
							</div>
						  	
						  	<div class="caja">
								<div class="error">
									{{form.especialidad.errors}}
								</div>
								<div>
								    <p class="especialidad">
								  		{% render_field form.especialidad|add_class:"feedback-input" name="especialidad" id="name" placeholder="Especialidad" %}
								  	</p>
							    </div>
							</div>

							<div class="caja">
								<div class="error">
									{{form.dependencia.errors}}
								</div>
								<div>
								    <p class="dependencia">
								  		{% render_field form.dependencia|add_class:"feedback-input" name="dependencia" id="name" placeholder="Dependencia" %}
								  	</p>
							    </div>
							</div>
						  	
						  	<div class="caja">
								<div class="error">
									{{form.curso.errors}}
								</div>
								<div>
								    <p class="curso">
								  		{% render_field form.curso|add_class:"feedback-input" name="curso" id="name" placeholder="Curso" %}
								  	</p>
							    </div>
							</div>
						  	
						  	<div class="clear"></div>
							<div class="submit">
						    	<input type="submit" value="Registrar" id="button-blue"/>
						    	<div class="ease"></div>
						  	</div>
						</form>
	            	</div>
	        	</div>
	    	</div>
	    </div>
    </section>
{% endblock content %}

templates/alumnos/alumno_list.html
{% extends "base.html" %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/tables.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">

    <section class="home full-height">

            <div id="main" class="container">
                <nav class="dropdownmenu">
                    <ul>
                        <li><a href="{% url 'alumnos:create_alumnos' %}">Nuevo Alumno</a></li>
                    </ul>  
                    <ul>
                        <li><a href="#">Registro Masivo</a></li>
                    </ul>   
                </nav>
                <h2>Lista de Alumnos</h2>
                <table class="width200">
                    <tbody>
                      <tr>
                        <th>N°</th>
                        <th>GRADO</th>
                        <th>ESPECIALIDAD</th>
                        <th>NOMBRES</th>
                        <th>APELLIDOS</th>
                        <th>CIP</th>
                        <th>DNI</th>
                        <th>DEPENDENCIA</th>
                        <th>CURSO</th>
                      </tr>
                    {% for alumno in object_list  %}
                        <tr>
                            <td>{{alumno.id}}</td>
                            <td>{{alumno.grado}}</td>
                            <td>{{alumno.especialidad}}</td>
                            <td>{{alumno.nombres}}</td>
                            <td>{{alumno.apellidos}}</td>
                            <td>{{alumno.cip}}</td>  
                            <td>{{alumno.dni}}</td>
                            <td>{{alumno.dependencia}}</td>
                            <td>{{alumno.curso}}</td>
                        </tr>
                    {% endfor %}
                      </tbody>
                </table>
            </div>
        </section>
{% endblock content %}

templates/alumnos/index.html
{% extends "base.html" %}

{% block content %}
	<section class="home full-height">

            <div class="container">
                <div class="row center">
                    <h1 id="welcome" class="col-10 title">Bienvenido a nuestro portal educativo</h1>

                    <div class="col-3 boton">
                        <a href="#" class="boton_a">Notas</a>
                    </div>

                    <div class="col-3 boton">
                        <a href="#" class="boton_a">Informes</a>
                    </div>
                </div>
            </div>

        </section>
	
{% endblock content %}