Academica/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('alumnos.urls', namespace="alumnos")),
    url(r'^', include('cursos.urls', namespace="cursos")),
    url(r'^', include('dependencias.urls', namespace="dependencias")),
    url(r'^', include('docentes.urls', namespace="docentes")),
    url(r'^', include('especialidades.urls', namespace="especialidades")),
    url(r'^', include('grados.urls', namespace="grados")),
    url(r'^', include('notas.urls', namespace="notas")),
    url(r'^', include('years.urls', namespace="years")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

especialidades/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^reportes/', views.hello_pdf, name='hello_pdf'),
    url(r'^especialidades/crear/', views.EspecialidadCreateView.as_view(), name='create_especialidades'),
    url(r'^especialidades/', views.EspecialidadListView.as_view(), name='list_especialidades'),
]

notas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
#    url(r'^$', views.hello_pdf, name='hello_pdf'),
]

especialidades/models.py
from __future__ import unicode_literals

from django.db import models

class Especialidad(models.Model):
	nombre = models.CharField(max_length=3)
	descripcion = models.CharField(max_length=255)

	def __str__(self):
		return self.nombre.encode('utf-8')

	def get_absolute_url(self):
		return u'/especialidades/'

especialidades/views.py
# coding: utf-8 
import os

from io import BytesIO

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4, cm
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, Table,TableStyle, Image
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from django.http import HttpResponse

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView

from .models import Especialidad

from django.shortcuts import render
from django.template import loader

class EspecialidadListView(ListView):
    model = Especialidad
    fields = '__all__'    

class EspecialidadCreateView(CreateView):
    model = Especialidad
    fields = '__all__'

def hello_pdf(request):
    # Create the HttpResponse headers with PDF.
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=Platzi-student-report.pdf'

    # Create the PDF object, using the BytesIO as its "file."
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)

    #Header
    c.setLineWidth(.3)
    c.setFont('Helvetica', 22)
    c.drawString(30, 750, 'Platzi')

    c.setFont('Helvetica', 12)
    c.drawString(30, 735, 'Report')

    c.setFont('Helvetica-Bold', 12)
    c.drawString(480, 750, "01/07/2016")
    #start X, height end y, heigth
    c.line(460, 747, 560, 747)

    #Students table
    students = [
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'},
        {'#':'1','name':'Angel Arteaga', 'b1':'3.4', 'b2':'2.4', 'b3':'5.4', 'total':'10'}
    ]

    #Table header
    styles = getSampleStyleSheet()
    styleBH = styles["Normal"]
    styleBH.alignment = TA_CENTER
    styleBH.fontSize = 10

    numero = Paragraph('''#''', styleBH)
    alumno = Paragraph('''Alumno''', styleBH)
    b1 = Paragraph('''BIM1''', styleBH)
    b2 = Paragraph('''BIM2''', styleBH)
    b3 = Paragraph('''BIM3''', styleBH)
    total = Paragraph('''Promedio''', styleBH)

    data = []

    data.append([numero, alumno, b1, b2, b3, total])

    #Table
    styleN = styles["BodyText"]
    styleN.alignment = TA_CENTER
    styleN.fontSize = 7

    high = 650
    for student in students:
    	this_student = [student['#'], student['name'], student['b1'], student['b2'], student['b3'], student['total']]
    	data.append(this_student)
    	high = high - 18

    #table size
    width, heigth = A4
    table = Table(data, colWidths=[1.9 * cm, 9.5 * cm, 1.9 * cm, 1.9 * cm, 1.9 * cm, 2 * cm])
    table.setStyle(TableStyle([#estilos de la tabla
    	('INNERGRID',(0,0),(-1, -1), 0.25, colors.blue),
    	('BOX', (0,0), (-1, -1), 0.25, colors.red),]))

    #pdf size
    table.wrapOn(c, width, heigth)
    table.drawOn(c, 30, high)
    c.showPage() #save page

    #save pdf
    c.save()

    # get the value of BytesIO buffer and write response	 
    pdf = buffer.getvalue()
    c.showPage()
    buffer.close()
    response.write(pdf)
    return response# Create your views here.

templates/especialidades/especialidad_form.html
{% extends "base.html" %}

{% block content %}
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/formularios.css' %}">
	
	<section class="home full-height">

        <div class="contenedor">
            <div class="row left">
                <h1 class="col-10 title">Registro de Especialidades</h1>
                <div id="form-main">
  					<div id="form-div">      
						<form class="form" action="" method="POST">
							{% csrf_token %}
					      	{% load widget_tweaks %}						 
							<div class="caja">
								<div class="error">
									{{form.nombre.errors}}
								</div>
								<div class="input">
									<p class="name">
								    	{% render_field form.nombre|add_class:"validate[required,custom[onlyLetter],length[0,100]] feedback-input" name="nombre" id="name" placeholder="Nombre de Especialidad" %}
								    </p>
							    </div>
							</div>
							<div class="caja">
								<div class="error">
									{{form.descripcion.errors}}
								</div>
								<div class="input">
								    <p class="descripcion">
								  		{% render_field form.descripcion|add_class:"validate[required,custom[onlyLetter],length[0,100]] feedback-input" name="descripcion" id="name" placeholder="Descripción" %}
								  	</p>
							    </div>
							</div>
						  	<div class="clear"></div>
							<div class="submit">
						    	<input type="submit" value="Registrar" id="button-blue"/>
						    	<div class="ease"></div>
						  	</div>
						</form>
	            	</div>
	        	</div>
	    	</div>
	    </div>
    </section>
{% endblock content %}

templates/especialidades/especialidad_list.html
{% extends "base.html" %}

{% block content %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/tables.css' %}">
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">

    <section class="home full-height">

            <div class="container">
                <nav class="dropdownmenu">
                    <ul>
                        <li><a href="{% url 'especialidades:create_especialidades' %}">Nueva especialidad</a></li>
                    </ul>  
                    <ul>
                        <li><a href="#">Registro Masivo</a></li>
                    </ul>   
                </nav>
                <h2>Lista de especialidad</h2>
                <table class="width200">
                    <tbody>
                      <tr>
                        <th>N°</th>
                        <th>ESPECIALIDAD</th>
                        <th>DESCRIPCIÓN</th>
                      </tr>
                    {% for especialidad in object_list  %}
                        <tr>
                            <td>{{especialidad.id}}</td>
                            <td>{{especialidad.nombre}}</td>
                            <td>{{especialidad.descripcion}}</td>
                        </tr>
                    {% endfor %}
                      </tbody>
                </table>
            </div>
        </section>
{% endblock content %}